"use strict";
//  Write a series of conditional tests. Print a statement describing each test and your prediction for the results of each test. Your code should look something like this:
Object.defineProperty(exports, "__esModule", { value: true });
let myName = "Muhammad Sufyan";
console.log("Is myName == Muhammad Sufyan? I predict true ");
console.log(myName === "Muhammad Sufyan");
let mobileNo = 3010484331;
console.log("Is mobileNo == 3010484231? I predict false");
console.log(mobileNo == 3010484231);
let isPass = true;
console.log("Is isPass == true ? I guess true");
console.log(isPass === true);
let houseOwner = "Ch Zahid";
console.log("Is houseOwner ==  CH Zahid? I predict false");
console.log(houseOwner === "CH Zahid");
let husband = "Muhammad Sufyan";
let wife = "Mehreen Fakhar";
console.log("IS husband == Muhammad Sufyan and wife == Mehreen Fakhar ? I predict true");
console.log(husband == "Muhammad Sufyan", wife == "Mehreen Fakhar");
let favCar = "Land Cruiser";
console.log("Is favCar == Fortuiner ? I predict false");
console.log(favCar == "Fortunier");
let myLaptop = "Dell 5300";
console.log("Is myLaptop == Hp 5300 ?  I predict false");
console.log(myLaptop == "Hp 5300");
let marks = 1098;
console.log("Is marks == 1000 ? I predict false");
console.log(marks == 1000);
